language: rust

os: osx

rust:
  - stable

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1

matrix:
  fast_finish: true
  include:
  - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
    os: osx
  - env: TARGET=x86_64-apple-ios DISABLE_TESTS=1
    os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx

script:
  - rustup target add $TARGET || true # Ignore failures when the target and toolchain are the same
  - cargo update
  - cargo build --verbose --target=$TARGET
  - if [[ -z $DISABLE_TESTS ]]; then cargo test --verbose; fi
